apiVersion: v1
kind: Service
metadata:
  name: pod-mutator-service
  namespace: default
spec:
  ports:
  - port: 443  # this is the port the Kubernetes API server will contact
    targetPort: 8443  # the port your webhook server listens on, usually 8443 for webhooks
  selector:
    app: pod-mutator  # This should match the label on your webhook server pods
